//-----------------------------------------------------------------------------
//  Copyright (C) Siemens AG 1998-2006  All Rights Reserved.  Confidential
//-----------------------------------------------------------------------------
//
// Project: NUMARIS/4
//
//    File: \n4\pkg\MrServers\MrImaging\seq\a_MiniFLASH\a_MiniFLASH.cpp
//
// Authors: Mark Brown;       SMS MED US CSG TDC;
//          Brian Dale;       SMS MED US CSG MR R&D;
//          Wolfgang Rehwald; SMS MED US CSG MR R&D;
//          Keith Heberlein;  SMS MED US CSG MR R&D;
//
//          Original Author:  Anonymous
//
//    Lang: C++
//
// Descrip: This is the demo sequence MiniFLASH.
//          DO NOT base any diagnosis on images generated by this sequence.
//
//////////////////////////////////////////////////////////////////////////////////////////
//
//                                MiniFLASH Sequence Diagram
//
//                       |-----------TE-------------|
//
//              RF --|sSRF01|--------------------------------------------
//
//              Gs -|sGSliSel|-|sGSliSelReph|-------------|sGSpoil|------
//
//              Gp ----------|sGPhasEnc|------------------|sGPhasEncRew|-
//
//              Gr ----------|sGReadDeph|-------|sGradRO|----------------
//
//             ADC -----------------------------|sADC01|-----------------
//
//                |------------------------------TR----------------------|
//
///////////////////////////////////////////////////////////////////////////////////////////

#include "MrServers/MrImaging/seq/MiniFLASH_UIF/a_MiniFLASH.h"
#include "MrServers/MrImaging/seq/MiniFLASH_UIF/a_MiniFLASH_UI.h"
#include "MrServers/MrMeasSrv/SeqIF/csequence.h"
#include "MrServers/MrImaging/libSeqSysProp/SysProperties.h"
#include "MrServers/MrImaging/seq/SystemProperties.h"        // Siemens system properties
#include "MrServers/MrImaging/ut/libsequt.h"                 // for mSEQTest

#ifdef WIN32
    #include "MrServers/MrMeasSrv/SeqIF/Sequence/Sequence.h"
#endif


// Macro: return S, if S is an error code
// (applies to functions returning MRRESULT-values)
#define OnErrorReturn(S) if(!MrSucceeded(S)) return(S)


#ifndef SEQ_NAMESPACE
    #error SEQ_NAMESPACE not defined
#endif



//  --------------------------------------------------------------------------
//
//  Name        :  SEQIF_DEFINE
//
//  Description :
///  \brief        Create instance of the sequence
//
//  Return      :  SeqIF *
//
//  --------------------------------------------------------------------------
#ifdef SEQUENCE_CLASS_MiniFLASH
    SEQIF_DEFINE (SEQ_NAMESPACE::MiniFlash)
#endif
using namespace SEQ_NAMESPACE;

MiniFlash::MiniFlash()
        : m_sSRF01              ("fl_templ_ex")
        , m_sSRF01zSet          ("sSRF01zSet")
        , m_sSRF01zNeg          ("sSRF01zNeg")
        , m_sADC01              ("sADC01")
        , m_sADC01zSet          ("sADC01zSet")
        , m_sADC01zNeg          ("sADC01zNeg")
        , m_sGSliSel            ("sGSliSel")
        , m_sGSliSelReph        ("sGSliSelReph")
        , m_sGradRO             ("sGradRO")
        , m_sGReadDeph          ("sGReadDeph")
        , m_sGPhasTab           ("sGPhasTab")
        , m_sGPhasTabRew        ("sGPhasTabRew")
        , m_sGSpoil             ("sGSpoil")
        , m_lLinesToMeasure     (0)
        , m_lLinesPerSec        (0)
        , m_lCenterLine         (0)
        , m_dRFSpoilIncrement   (0)
        , m_dRFSpoilPhase       (0)
        , m_dMinRiseTime        (100000)
        , m_dGradMaxAmpl        (0)
        , m_pUI                 (NULL) 
		//
		// all the UIF stuff	___FF___
#ifdef WIN32
		, m_pDiffusionGradient					(NULL)	// this is fine
		, m_DiffGradSchemeUIelmSet				(33)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_StdUIelmSet							(34)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_OptimGradMaxUIelmLong				(UIF_UI::REG_LongElement1)
		, m_VaporFaUIelmLong					(UIF_UI::REG_LongElement1)
		, m_OptimRiseTimeUIelmLong				(UIF_UI::REG_LongElement2)
		, m_DiffGradExtraCardUIelmSet			(35)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_OptimExtraCardUIelmSet				(36)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_ExtraCardUIelmSet					(37)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_VaporExtraCardUIelmSet				(38)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_DiffGradStdUIelmSet					(39)	// just numbers bigger than 14, to indicate it is not an element, but a  element set
		, m_lCurrentGradSchemeChoice			(UIF_UI::UIF_TrapGrad)
		, m_lCurrentExtraCardChoice				(UIF_UI::UIF_ExtraCardGrad)
		, m_StdCheckBoxUIelm					(UIF_UI::REG_CheckBox)//id=2
		, m_DiffGradB0CheckBoxUIelm				(UIF_UI::REG_CheckBox)//id=2
		, m_VaporCheckBoxUIelm					(UIF_UI::REG_CheckBox)//id=2
		, m_OptimInvisibleCheckBoxUIelm			(UIF_UI::REG_CheckBox)//id=2
		, m_StdDiffGradDurUIelmLong				(UIF_UI::REG_grad_dur)
		, m_StdNdirUIelmLong					(UIF_UI::REG_ndir)
		, m_StdNgvaUIelmLong					(UIF_UI::REG_ngval)
		, m_DiffGradDirUIelmLongArray			(UIF_UI::REG_LongArray2Element)
		, m_GvalueUIelmLongArray				(UIF_UI::REG_LongArray1Element)
		, m_VaporDelaysUIelmLongArray			(UIF_UI::REG_LongArray2Element)
		, m_VaporWSdeoptThrUIelmLongArray		(UIF_UI::REG_LongArray1Element)
		, m_OptimInvisibleUIelmLongArray1		(UIF_UI::REG_LongArray1Element)
		, m_OptimInvisibleUIelmLongArray2		(UIF_UI::REG_LongArray2Element)
		, m_VaporInvisibleUIelmLong2			(UIF_UI::REG_LongElement2)
		, m_VaporWSdeoptFractUIelmDoubleArray	(UIF_UI::REG_DoubleArrayElement)
		, m_OptimUIelmDoubleArray				(UIF_UI::REG_DoubleArrayElement)
		, m_DiffGradSchemeUIelmDoubleArray		(UIF_UI::REG_DoubleArrayElement)
		, m_UIelmSelBox							(UIF_UI::REG_Selection_Box)
		, m_InvisibleUIelmSelBox				(UIF_UI::REG_Selection_Box)
#endif

{
    // no further instructions...
}


MiniFlash::~MiniFlash() {
    if(NULL != m_pUI) {
        // delete the user interface (UI) instance (if a UI instance has been created)
        delete m_pUI;
        m_pUI = NULL;
    }
}



NLSStatus MiniFlash::initialize(SeqLim &rSeqLim) {
    // This string is intended to store, where we are in the code (used for debugging by the MRTRACE macro).
    static const char *ptModule = {"MiniFLASH::initialize"};

    // Default return value
    NLS_STATUS lStatus = SEQU__NORMAL;


    // -----------------------
    // Setting the hard limits
    // -----------------------


    // RF frequency is given as a long integer number in Hertz
    // The maximum allowed RF frequency is sufficient for 1H (hydrogen nuclei) in a 3-Tesla-system
    //                         (    min,       max)
    rSeqLim.setAllowedFrequency(8000000, 130850000);


    // The repetition time (TR) and echo time (TE) are given as long integer numbers in micro seconds.
    //                              (index,  min,        max,    increment,  default)
    rSeqLim.setTR                   (    0,  100,    5000000,           10,    20000);
    rSeqLim.setTE                   (    0,  100,     100000,           10,    10000);
    rSeqLim.setBandWidthPerPixel    (    0,   80,        900,           10,      260);


    // The flip angle is given as a double number in degrees.
    //                              (        min,        max,    increment,  default)
    rSeqLim.setFlipAngle            (       10.0,       90.0,          1.0,   15.000);


    // The base resolution tells how many samples in readout direction are acquired in k-space. The increment-value
    // is not set directly. Instead, a key is used which is connected to values of 16, 32, 64, etc. The allowed
    // values can be looked up in "kSpaceDefines.h".
    //                              (        min,        max,    increment,  default)
    rSeqLim.setBaseResolution       (         64,        512,  SEQ::INC_64,      128); //INC_BASE2 also available


    // The field-of-view (FOV) is given as double numbers in mm.
    //                              (        min,        max,    increment,  default)
    rSeqLim.setReadoutFOV           (        100,        500,            1,      300);
    rSeqLim.setPhaseFOV             (        100,        500,            1,      300);


    // Here, we set the number of lines in phase encoding(PE)-direction.
    //                              (        min,        max,    increment,  default)
    rSeqLim.setPELines              (         32,       1024,            1,      128);


    // The MiniFLASH sequence is intended for single-slice measurements only.
    //                              (        min,        max,    increment,  default)
    rSeqLim.setSlices               (          1,          1,            1,        1);


    // The slice thickness is given as a double number in mm.
    //                              (        min,        max,    increment,  default)
    rSeqLim.setSliceThickness       (      2.000,     10.000,        0.500,    5.000);


	///////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//									initialisation of UI Specia Card								___FF___
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifdef WIN32
    _UIF_Register (&rSeqLim) ;//																		___FF___
#endif

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//									initialisation of Factory stuff									___FF___
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////
	initializeFactoryStuff();

#ifdef WIN32
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//									initialisation of UI staff										___FF___
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////
	initializeUIelementSets();
#endif				

    // --------------------------------------
    // Instantiation of the MiniFlashUI-class
    // --------------------------------------

    

    // MRRESULT_SEV is a mask for the "severity" bits. This if-statement checks whether the severity bits
    // are set (which indicates that something went wrong).
    if((MRRESULT_SEV & (lStatus = createUI(rSeqLim))) == MRRESULT_SEV) {

        // The MRTRACE macro is used to log information for debugging purposes
        MRTRACE("Instantiation of MiniFlashUI class failed!");
        return lStatus;
    }


    // This compiler directive restricts this code to the HOST version dll.
    // In this way the same source code can be compiled for both the Host and the MARS.
#ifdef WIN32
    if(NULL == m_pUI) {
        MRTRACE("MiniFlashUI object pointer is null (creation failed probably)!");
        return ( SEQU_ERROR );
    }


    // ----------------------------------------------
    // Declaration of pointer to UI parameter classes
    // ----------------------------------------------
    lStatus = m_pUI->registerUI(rSeqLim);

    if(MrSeverity(lStatus) != MRRESULT_SUCCESS) {
        MRTRACE("Registering MiniFlashUI object failed! Errorcode: %i", lStatus);
        return lStatus;
    }

    // -----------------------------------------------------------------
    // file containing the default postprocessing protocol (EVAProtocol)
    // -----------------------------------------------------------------
    
    // The _T(x) macro deals with the unicode conversion of strings.
    rSeqLim.setDefaultEVAProt (_T("%SiemensEvaDefProt%\\Inline\\Inline.evp"));
#endif
    return lStatus;
}



//. -------------------------------------------------------------------------
//.. fSEQPrep: prepare real time elements and calculate energy and timing
//. -------------------------------------------------------------------------
NLSStatus MiniFlash::prepare(MrProt &rMrProt, SeqLim &rSeqLim, MrProtocolData::SeqExpo &rSeqExpo)
{
    static const char *ptModule = {"MiniFlash::prepare"};
    NLS_STATUS   lStatus = SEQU__NORMAL;                     // * Return status *
    long         lTEFil;
    double       dMeasureTimeUsec      = 0.0;


    // --------------------
    // get some information
    // --------------------
    
    OnErrorReturn(rMrProt.kSpace().linesToMeasure(m_lLinesToMeasure));


    m_lCenterLine  = rMrProt.kSpace().echoLine();

    m_dMinRiseTime = SysProperties::getGradMinRiseTime(rMrProt.gradSpec().mode());
    m_dGradMaxAmpl = SysProperties::getGradMaxAmpl(rMrProt.gradSpec().mode());
    dMeasureTimeUsec = (double)m_lLinesToMeasure * rMrProt.tr()[0];

	// make sure that m_lLinesPerSec is at least 1.
    m_lLinesPerSec =  std::max<long>(1,long(m_lLinesToMeasure * 1000000. /dMeasureTimeUsec));





    // ------------------------------------------------
    // Preparation of all required real time components
    // ------------------------------------------------
    rSeqExpo.setRelevantReadoutsForMeasTime(m_lLinesToMeasure / m_lLinesPerSec);

    //. Prepare RF pulse
    m_sSRF01.setTypeExcitation   ();
    m_sSRF01.setDuration         (2560) ;
    m_sSRF01.setFlipAngle        (rMrProt.flipAngle());
    m_sSRF01.setInitialPhase     (0);
    m_sSRF01.setThickness        (rMrProt.sliceSeries().aFront().thickness());
    m_sSRF01.setSamples          (128);
    m_sSRF01.setBandwidthTimeProduct(2.70);
    if(! m_sSRF01.prepSinc(rMrProt,rSeqExpo)) return (m_sSRF01.getNLSStatus());

    //. Prepare ADC
    m_sADC01.setColumns (rMrProt.kSpace().getlBaseResolution());
    m_sADC01.setDwellTime ((long)((rMrProt.rxSpec().effDwellTime(rSeqLim.getReadoutOSFactor())[0]) + 0.5));
    m_sADC01.getMDH().setKSpaceCentreColumn((unsigned short)(rMrProt.kSpace().getlBaseResolution()/2));
    //. Prepare readout gradient
    if(!m_sGradRO.prepRO(600,(fSDSRoundUpGRT(m_sADC01.getDuration()+600)),
        600,rMrProt,m_sADC01.getDwellTime()))return(m_sGradRO.getNLSStatus());

    //. Prepare and check phase encoding
    if(!m_sGPhasTab.prepPE(600, 1000 , 600, rMrProt, SEQ::DIR_ASCENDING, 0.0,
        m_lLinesToMeasure - m_lCenterLine -1))return(m_sGPhasTab.getNLSStatus());
    if(!m_sGPhasTab.check()) return(m_sGPhasTab.getNLSStatus());
    if(!m_sGPhasTab.prepPE(600, 1000, 600, rMrProt, SEQ::DIR_ASCENDING, 0.0,
        - m_lCenterLine)) return(m_sGPhasTab.getNLSStatus());
    if(!m_sGPhasTab.check()) return(m_sGPhasTab.getNLSStatus());

    // Copy info to PE rewinder
    m_sGPhasTabRew=m_sGPhasTab;

    //. Prepare and check slice selection gradient
    if(!m_sGSliSel.prepAmplitude(600, fSDSRoundUpGRT(m_sSRF01.getDuration()+600),
        600, m_sSRF01.getGSAmplitude()))return(m_sGSliSel.getNLSStatus());
    if (! m_sGSliSel.check() ) return (m_sGSliSel.getNLSStatus());

    //. Check if gradients fit into TE
    long lTEfil = fSDSRoundDownGRT( rMrProt.te()[0]
        - (m_sSRF01.getDuration()/2  + m_sGSliSel.getRampDownTime()
        + m_sADC01.getDuration()/2 + m_sGradRO.getRampUpTime()));
    if ( lTEfil <= 0 ) return SBB_NEGATIV_TEFILL ;

    //. Prepare and check slice rephase gradient
    m_sGSliSelReph.setMaxMagnitude(m_dGradMaxAmpl);
    m_sGSliSelReph.setMinRiseTime(m_dMinRiseTime);
    if (! m_sGSliSelReph.prepSymmetricTOTShortestTime(-m_sGSliSel.getMomentum(
        m_sGSliSel.getDuration()-m_sSRF01.getDuration()/2,m_sGSliSel.getTotalTime())))
        return (m_sGSliSelReph.getNLSStatus());

    //. Prepare and check readout dephasing gradient
    m_sGReadDeph.setMaxMagnitude(m_dGradMaxAmpl);
    m_sGReadDeph.setMinRiseTime(m_dMinRiseTime);
    if (! m_sGReadDeph.prepSymmetricTOTShortestTime(-m_sGradRO.getMomentum(
        0,(long)(m_sGradRO.getRampUpTime() + m_sADC01.getDuration()/2))))
        return (m_sGReadDeph.getNLSStatus());

    //. Prepare and check spoiler gradient
    m_sGSpoil.setMaxMagnitude(m_dGradMaxAmpl);
    m_sGSpoil.setMinRiseTime (m_dMinRiseTime);
    if(!m_sGSpoil.prepSymmetricTOTExactMomentum(m_sGSliSel.getMomentumTOT()/2,
        m_sGPhasTabRew.getTotalTime())) return (m_sGSpoil.getNLSStatus());

    //. Check if gradients fit into TE
    long lTENeed =   std::max(m_sGPhasTab.getTotalTime(), m_sGReadDeph.getTotalTime())
        -m_sGSliSel.getRampDownTime();
    lTENeed =   std::max( lTENeed , m_sGSliSelReph.getTotalTime() ) ;
    lTENeed += (long)(m_sSRF01.getDuration()/2 + m_sGSliSel.getRampDownTime()
        + m_sGradRO.getRampUpTime() + m_sADC01.getDuration()/2);
    lTEFil= long(rMrProt.te()[0] - lTENeed);
    if (lTEFil< 0 ) return SBB_NEGATIV_TEFILL ;

    //. Determine the start time of some RT elements and check if gradients fit into TR
    m_sGradRO.setStartTime(fSDSRoundUpGRT(m_sGSliSel.getDuration()
        - m_sSRF01.getDuration()/2 + rMrProt.te()[0]
        - m_sADC01.getRoundedDuration()/2 - m_sGradRO.getRampUpTime()));
    if(rMrProt.tr()[0]<(m_sGradRO.getStartTime()+m_sGradRO.getDuration()
        +std::max(m_sGPhasTabRew.getTotalTime(),m_sGSpoil.getTotalTime())))
        return SBB_NEGATIV_TRFILL ;
    m_sADC01.setStartTime(m_sGradRO.getStartTime() + m_sGradRO.getRampUpTime());

    // Set receiver gain
    OnErrorReturn(fSSLSetRxGain(K_RX_GAIN_CODE_HIGH,rMrProt,rSeqLim));
    // Prepare the slice position array
    OnErrorReturn(fSUPrepSlicePosArray (rMrProt, rSeqLim, m_asSLC));

    // Set sequence string for display in images
    fSUSetSequenceString              ("fl", rMrProt, rSeqExpo);

    //. Fill export section
    rSeqExpo.setRFEnergyInSequence_Ws(m_lLinesToMeasure
        * m_sSRF01.getPulseEnergyWs());
    rSeqExpo.setMeasuredPELines      (m_lLinesToMeasure);
    rSeqExpo.setMeasureTimeUsec      (dMeasureTimeUsec);
    rSeqExpo.setTotalMeasureTimeUsec (dMeasureTimeUsec);
    rSeqExpo.setPCAlgorithm          (SEQ::PC_ALGORITHM_NONE);
    rSeqExpo.setOnlineFFT            (SEQ::ONLINE_FFT_PHASE);
    rSeqExpo.setICEProgramFilename   ("%SiemensIceProgs%\\IceProgramOnline2D");    // Only 2D reconstruction allowed
    
    rSeqExpo.setICEProgramParam(ICE_PROGRAM_PARA_SHOW_OFFLINE, SEQ::SO_SHOW_NO);


#ifdef WIN32

	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//								UI SPECIAL CARD														___FF___
	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//
	// initiaisation is performed in the usual Siemens way. 
    if(! _UIF_Init (&rMrProt, &rSeqLim, m_pDiffusionGradSchemeUIConfigurator, m_lCurrentGradSchemeChoice ) )return SEQU_ERROR; //				___FF___

#endif	

	checkAndRefreshInCaseOfSelBoxesVariation(rMrProt, rSeqLim);
	m_pDiffusionGradient=m_pDiffusionGradientScheme->getGradientPulse(rMrProt);

	return (lStatus);
}

//. -------------------------------------------------------------------------
//.. fSEQCheck: check lines at the border of k-space (gradient overflow, GSWD)
//. -------------------------------------------------------------------------
NLSStatus MiniFlash::check(MrProt &rMrProt, SeqLim &rSeqLim, MrProtocolData::SeqExpo &rSeqExpo, SEQCheckMode * /*pSEQCheckMode*/)
{
    
    static const char *ptModule = {"MiniFlash::check"};
    NLS_STATUS   lStatus = SEQU__NORMAL;
    long        lL                = 0;
    long        alLCk[4]          = {0, 1, rSeqExpo.getMeasuredPELines() - 2, rSeqExpo.getMeasuredPELines() - 1};
    while (lL < 4 )
    {
        OnErrorReturn(runKernel(rMrProt,rSeqLim,rSeqExpo,KERNEL_CHECK,0, 0, alLCk[lL]));
        lL++;
    }
    return(lStatus);
}

//. -------------------------------------------------------------------------
//.. fSEQRun: run the sequence
//. -------------------------------------------------------------------------
NLSStatus MiniFlash::run(MrProt  &rMrProt, SeqLim &rSeqLim, MrProtocolData::SeqExpo &rSeqExpo)
{
    static const char *ptModule = {"MiniFlash::run"};
    NLS_STATUS lStatus          = SEQU__NORMAL;
    //. Initialize sequence test
    if(IS_UNIT_TEST_ACTIVE(rSeqLim))
    {
        mSEQTest(rMrProt,rSeqLim,rSeqExpo,RTEB_ORIGIN_fSEQRunStart,0,0,0,0,0);
    }
    long lLine;
    long lCurrKernelCalls = 0;

    //. Send the delay between measurements
    OnErrorReturn(fSBBMeasRepetDelaysRun ( rMrProt, rSeqLim, rSeqExpo, 0 ));
    // Fill some entries of the measurement data header
    m_sADC01.getMDH().setEvalInfoMask (m_sADC01.getMDH().getEvalInfoMask() | MDH_ONLINE) ;
    m_sADC01.getMDH().setKSpaceCentreLineNo    ((unsigned short)rMrProt.kSpace().echoLine());
    m_sADC01.getMDH().setKSpaceCentrePartitionNo (0);

    if(IS_UNIT_TEST_ACTIVE(rSeqLim))
    {
        mSEQTest (rMrProt, rSeqLim, rSeqExpo, RTEB_ClockInitTR, 0, 0, m_asSLC[0].getSliceIndex(), 0, 0);
    }

    //. Loop over lines
    for (lLine = 0; lLine < m_lLinesToMeasure; lLine++ )
    {
        lCurrKernelCalls ++;
        // Fill some entries of the measurement data header

        if(!(lCurrKernelCalls % m_lLinesPerSec)) m_sADC01.setRelevantForMeasTime();
        m_sADC01.getMDH().setFirstScanInSlice( lLine == 0 );
        m_sADC01.getMDH().setLastScanInSlice ( lLine == m_lLinesToMeasure - 1);
        m_sADC01.getMDH().setLastScanInConcat( lLine == m_lLinesToMeasure - 1);
        m_sADC01.getMDH().setLastScanInMeas  ( lLine == m_lLinesToMeasure - 1);


        // Call Kernel function
        OnErrorReturn(runKernel(rMrProt, rSeqLim,
            rSeqExpo,KERNEL_IMAGE,0, 0, lLine));
    }
    if(IS_UNIT_TEST_ACTIVE(rSeqLim))
    {
        mSEQTest(rMrProt,rSeqLim,rSeqExpo,RTEB_ORIGIN_fSEQRunFinish,0,0,0,0,0);
    }
    return(SEQU__NORMAL);
}


//. -------------------------------------------------------------------------
//.. runKernel
//. -------------------------------------------------------------------------
NLS_STATUS MiniFlash::runKernel(MrProt &rMrProt, SeqLim &rSeqLim,
                             MrProtocolData::SeqExpo &rSeqExpo, long lKernelMode, long /* lSlice */, long /* lPartition */, long lLine)
{
    static const char *ptModule = {"MiniFlash::runKerenl"};
    NLS_STATUS         lStatus  = SEQU__NORMAL;
    //. Prepare Phase encoding and rewinder
    if(! m_sGPhasTab.prepPE(rMrProt,lLine-m_lCenterLine))
        return m_sGPhasTab.getNLSStatus();
    if(! m_sGPhasTabRew.prepPE(rMrProt, m_lCenterLine-lLine) )
        return m_sGPhasTabRew.getNLSStatus();

    //. Fill measurement data header
    m_sADC01.getMDH().setClin            ((unsigned short)lLine);
    m_sADC01.getMDH().setPhaseFT         (lLine == m_lLinesToMeasure - 1);

    //. Prepare FrequencyPhase objects of the RF pulse
    m_sSRF01zSet.prepSet (m_asSLC[0], m_sSRF01) ;
    m_sSRF01zNeg.prepNeg (m_asSLC[0], m_sSRF01) ;

    //. Prepare FrequencyPhase objects of the ADC
    m_sADC01zSet.prepSet (m_asSLC[0], m_sADC01, m_sGradRO,lLine-m_lCenterLine,0) ;
    m_sADC01zNeg.prepNeg (m_asSLC[0], m_sADC01, m_sGradRO,lLine-m_lCenterLine,0) ;

    // Calculate additional phase needed for RF spoiling and add to FreqPhase
    m_dRFSpoilIncrement += RFSPOIL_INCREMENTdeg ;
    m_dRFSpoilPhase += m_dRFSpoilIncrement ;
    m_dRFSpoilPhase     = fmod(m_dRFSpoilPhase,     (double) RFMAXPHASEdeg);
    m_dRFSpoilIncrement = fmod(m_dRFSpoilIncrement, (double) RFMAXPHASEdeg);

    m_sADC01zSet.increasePhase(m_dRFSpoilPhase);
    m_sADC01zNeg.decreasePhase(m_dRFSpoilPhase);

    m_sSRF01zSet.increasePhase(m_dRFSpoilPhase);
    m_sSRF01zNeg.decreasePhase(m_dRFSpoilPhase);

    //. Initialize real time event block with actual rotation matrix
    fRTEBInit( m_asSLC[0].getROT_MATRIX());

    //- ***************************************************** S E Q U E N C E   T I M I N G **********************************************************************
    //- *                             Start Time                   |      NCO     |    SRF   |    ADC   |                Gradient Events                 | Sync
    //- *                               (usec)                     |     Event    |   Event  |   Event  |      phase     |     read     |      slice     | Event
    //- *fRTEI(                                                    ,              ,          ,          ,                ,              ,                ,      );
    //- **********************************************************************************************************************************************************
    fRTEI ( 0                                                      ,             0,         0,         0,               0,             0,     &m_sGSliSel,    0 );
    fRTEI ( m_sGSliSel.getDuration() - m_sSRF01.getDuration()      , &m_sSRF01zSet, &m_sSRF01,         0,               0,             0,               0,    0 );
    fRTEI ( m_sGSliSel.getDuration()                               , &m_sSRF01zNeg,         0,         0,    &m_sGPhasTab, &m_sGReadDeph,               0,    0 );
    fRTEI ( m_sGSliSel.getTotalTime()                              ,             0,         0,         0,               0,             0, &m_sGSliSelReph,    0 );
    fRTEI ( m_sGradRO.getStartTime()                               ,             0,         0,         0,               0,    &m_sGradRO,               0,    0 );
    fRTEI ( m_sADC01.getStartTime()                                , &m_sADC01zSet,         0, &m_sADC01,         m_pDiffusionGradient,             0,               0,    0 );
    fRTEI ( m_sADC01.getStartTime() + m_sADC01.getRoundedDuration(), &m_sADC01zNeg,         0,         0,               0,             0,               0,    0 );
    fRTEI ( m_sGradRO.getStartTime() + m_sGradRO.getDuration()     ,             0,         0,         0, &m_sGPhasTabRew,             0,      &m_sGSpoil,    0 );
    fRTEI ( rMrProt.tr()[0]                                        ,             0,         0,         0,               0,             0,               0,    0 );

    //. Call sequence unit test
    if(IS_UNIT_TEST_ACTIVE(rSeqLim))
    {
        if (lKernelMode == KERNEL_CHECK)
            mSEQTest(rMrProt, rSeqLim, rSeqExpo, RTEB_ORIGIN_fSEQCheck,  10, lLine, m_asSLC[0].getSliceIndex(), 0, 0);
        else
            mSEQTest(rMrProt, rSeqLim, rSeqExpo, RTEB_ORIGIN_fSEQRunKernel,10,lLine,m_asSLC[0].getSliceIndex(), 0, 0);
        mSEQTest    (rMrProt, rSeqLim, rSeqExpo, RTEB_ClockCheck,        10, lLine, m_asSLC[0].getSliceIndex(), 0, 0);
    }
    //. End real time event block
    OnErrorReturn((NLS_STATUS)fRTEBFinish());

    return(lStatus);
}


NLS_STATUS MiniFlash::createUI (SeqLim&)
{
    #ifdef WIN32

        static const char *ptModule = {"MiniFlash::createUI"};

        //  ----------------------------------------------------------------------
        //  Delete existing instance if necessary
        //  ----------------------------------------------------------------------
        if(m_pUI)  {
            delete m_pUI;
            m_pUI = NULL;
        }



        //  ----------------------------------------------------------------------
        //  Instantiation of the UI class
        //  ----------------------------------------------------------------------
        try  {
            m_pUI = new MiniFlashUI();
        }

        catch (...)  {
            delete m_pUI;
            m_pUI = NULL;

            TRACE_PUT1(TC_ALWAYS, TF_SEQ,"%s: Cannot instantiate UI class !", ptModule);
            return ( SEQU_ERROR );
        }

    #endif

    return ( SEQU_NORMAL );

}   // end: MiniFlash::createUI



const MiniFlashUI* MiniFlash::getUI (void) const
{
    return ( m_pUI );
}

NLSStatus MiniFlash::initializeFactoryStuff(void)
{
	// During initialisation, we configure a default Factory. It will be responsible to return the right UI, Gradient, 
	// UI configuration, and so on. depending on a SLECTION BOX choice. 
	//
	// The static function of class AbstractDiffusionGradientSchemeFactory is the one we use to retrieve the right Factory class 
	// (among the different Factory ones, each one providing the right family of objects) depending on SELECTION BOX choice. 
	// NOTE: By declaring a function member as static, you make it independent of any particular object of the class. 
	// A static member function can be called even if no objects of the class exist and the static functions are accessed 
	// using only the class name and the scope resolution operator ::.
	//m_pDiffusionGradientSchemeFactory=AbstractDiffusionGradientSchemeFactory::getFactory(UIF_UI::UIF_FWFGrad);//default Gradient Scheme is TRAP
	m_pDiffusionGradientSchemeFactory = AbstractDiffusionGradientSchemeFactory::getFactory(m_lCurrentGradSchemeChoice);	//default Gradient Scheme is TRAP


	// the right factory returns the righr GradScheme
	m_pDiffusionGradientScheme=m_pDiffusionGradientSchemeFactory->getGradientScheme();
	
	// We use an interface UI configuration object to handle correctly the Special Card UI in function of our choice. 
	// e.g. m_lDefault=500; m_lMin=10;  m_lMax=1000; m_lInc=10; m_pLabel="OscGrad label";
	// the right UI configuration class is returned by the right Factory determined  by the SELECTION BOX choice.  
	m_pDiffusionGradSchemeUIConfigurator=m_pDiffusionGradientSchemeFactory->getUIConfigurator();
	
	
	return ( SEQU_NORMAL );
}

#ifdef WIN32
// here we initialise all the sets we need to manage dynamically the UI								___FF___
// We use a GLOBAL object of type UIelementSet (in combination with the usual global 
// function handlers) to handle the UI behaviour // depending on the user choices 
// (EXTRA CARD SEL BOX and GRAD SCHEME SEL BOX). // It happens thanks to UI configurator 
// and UIConfig objects
NLSStatus MiniFlash::initializeUIelementSets(void)	//												___FF___
{

	

	// ----------------------------------
	// THE DIFF GRAD EXTRA CARD UIELEMENT SET
	// ----------------------------------

	//----------------------------------
	// THE DIFF GRAD SCHEME UIELEMENT SET
	//----------------------------------
	m_DiffGradSchemeUIelmSet=m_pDiffusionGradSchemeUIConfigurator->getUIConfig();

	// ----------------------------------
	// THE DIFF GRAD STD UIELEMENT SET
	// ----------------------------------
	// Gradient directions Array
	m_DiffGradDirUIelmLongArray.m_lMin.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lMin.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lMin.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lMin.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lMin.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lMin.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lMax.push_back(16);
	m_DiffGradDirUIelmLongArray.m_lMax.push_back(16);
	m_DiffGradDirUIelmLongArray.m_lMax.push_back(16);
	m_DiffGradDirUIelmLongArray.m_lMax.push_back(16);
	m_DiffGradDirUIelmLongArray.m_lMax.push_back(16);
	m_DiffGradDirUIelmLongArray.m_lMax.push_back(16);
	m_DiffGradDirUIelmLongArray.m_lInc.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lInc.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lInc.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lInc.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lInc.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lInc.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lDefault.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lDefault.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lDefault.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lDefault.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lDefault.push_back(1);
	m_DiffGradDirUIelmLongArray.m_lDefault.push_back(1);
	m_DiffGradDirUIelmLongArray.m_pLabel="Grad directions";
	m_DiffGradDirUIelmLongArray.m_lWMBindex=UIF_UI::WMB_GdirLongArray_Start; 
	m_DiffGradDirUIelmLongArray.m_lArraySize=6;
	// G values Array
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMin.push_back(-300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lMax.push_back(300);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lInc.push_back(1);
	m_GvalueUIelmLongArray.m_lDefault.push_back(5);
	m_GvalueUIelmLongArray.m_lDefault.push_back(10);
	m_GvalueUIelmLongArray.m_lDefault.push_back(15);
	m_GvalueUIelmLongArray.m_lDefault.push_back(20);
	m_GvalueUIelmLongArray.m_lDefault.push_back(25);
	m_GvalueUIelmLongArray.m_lDefault.push_back(30);
	m_GvalueUIelmLongArray.m_lDefault.push_back(35);
	m_GvalueUIelmLongArray.m_lDefault.push_back(40);
	m_GvalueUIelmLongArray.m_lDefault.push_back(45);
	m_GvalueUIelmLongArray.m_lDefault.push_back(5);
	m_GvalueUIelmLongArray.m_pLabel="g";
	m_GvalueUIelmLongArray.m_lWMBindex=UIF_UI::WMB_GvalueLongArray_Start; 
	m_GvalueUIelmLongArray.m_lArraySize=10;
	// b0 check box
	m_DiffGradB0CheckBoxUIelm.m_pLabel="b0";
	m_DiffGradB0CheckBoxUIelm.m_lWMBindex=UIF_UI::WMB_b0CheckBox;
	// a double array
	m_DiffGradSchemeUIelmDoubleArray.m_dMin.push_back(0);
	m_DiffGradSchemeUIelmDoubleArray.m_dMin.push_back(0);
	m_DiffGradSchemeUIelmDoubleArray.m_dMax.push_back(1);
	m_DiffGradSchemeUIelmDoubleArray.m_dMax.push_back(1);
	m_DiffGradSchemeUIelmDoubleArray.m_dInc.push_back(0.1);
	m_DiffGradSchemeUIelmDoubleArray.m_dInc.push_back(0.1);
	m_DiffGradSchemeUIelmDoubleArray.m_dDefault.push_back(1);
	m_DiffGradSchemeUIelmDoubleArray.m_dDefault.push_back(1);
	m_DiffGradSchemeUIelmDoubleArray.m_pLabel="Grad double";
	m_DiffGradSchemeUIelmDoubleArray.m_lWMBindex=UIF_UI::WMB_GradDoubleArray_Start; // 0->16, DOUBLE
	m_DiffGradSchemeUIelmDoubleArray.m_lArraySize=2;
	// COMPOSING DIFF GRAD STD UIELEMENT SET
	m_DiffGradStdUIelmSet.addElement(&m_DiffGradDirUIelmLongArray);		// will go on GRAD CARD (and VAPOR will also have one)
	m_DiffGradStdUIelmSet.addElement(&m_GvalueUIelmLongArray);	// will go on GRAD CARD (and VAPOR will also have one)
	m_DiffGradStdUIelmSet.addElement(&m_DiffGradB0CheckBoxUIelm);
	m_DiffGradStdUIelmSet.addElement(&m_DiffGradSchemeUIelmDoubleArray);
	// COMPOSING DIFF GRAD EXTRA CARD UI ELEMENT SET
	m_DiffGradExtraCardUIelmSet.addElement(&m_DiffGradSchemeUIelmSet);
	m_DiffGradExtraCardUIelmSet.addElement(&m_DiffGradStdUIelmSet);



	// ----------------------------------
	// THE VAPOR UIELEMENT SET
	// ----------------------------------
	// VAPOR FA
	//rTool.createLongParameter      (WIPVAPOR_FA,    rSeqLim, "VAPOR FA", "deg", 5, 180, 5, 90);
	m_VaporFaUIelmLong.m_lMin.push_back(5); 
	m_VaporFaUIelmLong.m_lMax.push_back(180);
	m_VaporFaUIelmLong.m_lInc.push_back(5);
	m_VaporFaUIelmLong.m_lDefault.push_back(90);
	m_VaporFaUIelmLong.m_pLabel="VAPOR FA";
	m_VaporFaUIelmLong.m_lWMBindex=UIF_UI::WMB_VAPOR_FA; 
	// VAPOR CHECK BOX
	m_VaporCheckBoxUIelm.m_pLabel="VAPOR";						
	m_VaporCheckBoxUIelm.m_lWMBindex=UIF_UI::WMB_VAPORCheckBox;	
	// VAPOR invisible long 2 (not used)
	m_VaporInvisibleUIelmLong2.m_lMin.push_back(5); 
	m_VaporInvisibleUIelmLong2.m_lMax.push_back(180);
	m_VaporInvisibleUIelmLong2.m_lInc.push_back(5);
	m_VaporInvisibleUIelmLong2.m_lDefault.push_back(90);
	m_VaporInvisibleUIelmLong2.m_pLabel="I should be invisible";
	m_VaporInvisibleUIelmLong2.m_lWMBindex=UIF_UI::WMB_InvisibleStuff; // all LONG invisible share thiw WMB slot, we need to initialise it just once (but it will never be uesd)
	m_VaporInvisibleUIelmLong2.m_bIsAvailable=false;
	// Vapor Delays array 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMin.push_back(0); 
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lMax.push_back(200);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lInc.push_back(1);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(150);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(100);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(146);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(105);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(106);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(68);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(72);
	m_VaporDelaysUIelmLongArray.m_lDefault.push_back(28);
	m_VaporDelaysUIelmLongArray.m_pLabel="VAPOR delays";
	m_VaporDelaysUIelmLongArray.m_lWMBindex=UIF_UI::WMB_VAPORdelaysLongArray_Start; 
	m_VaporDelaysUIelmLongArray.m_lArraySize=8;
    // WS deopt array
	m_VaporWSdeoptThrUIelmLongArray.m_lMin.push_back(0);
	m_VaporWSdeoptThrUIelmLongArray.m_lMin.push_back(0);
	m_VaporWSdeoptThrUIelmLongArray.m_lMax.push_back(200);
	m_VaporWSdeoptThrUIelmLongArray.m_lMax.push_back(200);
	m_VaporWSdeoptThrUIelmLongArray.m_lInc.push_back(1);
	m_VaporWSdeoptThrUIelmLongArray.m_lInc.push_back(1);
	m_VaporWSdeoptThrUIelmLongArray.m_lDefault.push_back(150);
	m_VaporWSdeoptThrUIelmLongArray.m_lDefault.push_back(100);
	m_VaporWSdeoptThrUIelmLongArray.m_pLabel="VAPOR WS deopt";
	m_VaporWSdeoptThrUIelmLongArray.m_lWMBindex=UIF_UI::WMB_WSdeoptLongArray_Start; 
	m_VaporWSdeoptThrUIelmLongArray.m_lArraySize=2;
	// DOUBLE ARRAY
	m_VaporWSdeoptFractUIelmDoubleArray.m_dMin.push_back(0);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dMin.push_back(0);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dMax.push_back(1);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dMax.push_back(1);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dInc.push_back(0.1);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dInc.push_back(0.1);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dDefault.push_back(1);
	m_VaporWSdeoptFractUIelmDoubleArray.m_dDefault.push_back(1);
	m_VaporWSdeoptFractUIelmDoubleArray.m_pLabel="WS deopt fraction";
	m_VaporWSdeoptFractUIelmDoubleArray.m_lWMBindex=UIF_UI::WMB_WSdeoptFractDoubleArray_Start; // 0->16, DOUBLE
	m_VaporWSdeoptFractUIelmDoubleArray.m_lArraySize=2;
	// VAPOR SELECTION BOX ---> invisible
	m_InvisibleUIelmSelBox.m_sOptions.push_back("meaningless option");
	m_InvisibleUIelmSelBox.m_pLabel="I should be invisible";
	m_InvisibleUIelmSelBox.m_lWMBindex=UIF_UI::WMB_InvisibleStuff; 
	m_InvisibleUIelmSelBox.m_lNofOptions=1;
	m_InvisibleUIelmSelBox.m_bIsAvailable=false;
	// CIMPOSING VAPOR EXTRA CARD UI ELEMENT SET
	m_VaporExtraCardUIelmSet.addElement(&m_VaporCheckBoxUIelm);
	m_VaporExtraCardUIelmSet.addElement(&m_VaporFaUIelmLong);
	m_VaporExtraCardUIelmSet.addElement(&m_VaporWSdeoptThrUIelmLongArray);	// will go on GRAD CARD (and VAPOR will also have one)
	m_VaporExtraCardUIelmSet.addElement(&m_VaporDelaysUIelmLongArray);		// will go on GRAD CARD (and VAPOR will also have one)
	m_VaporExtraCardUIelmSet.addElement(&m_VaporInvisibleUIelmLong2);
	m_VaporExtraCardUIelmSet.addElement(&m_VaporWSdeoptFractUIelmDoubleArray);
	m_VaporExtraCardUIelmSet.addElement(&m_InvisibleUIelmSelBox);



	// ----------------------------------
	// THE OPTIM UIELEMENT SET
	// ----------------------------------
	// MAx Grad									REG Long Elm 1
	m_OptimGradMaxUIelmLong.m_lMin.push_back(40); 
	m_OptimGradMaxUIelmLong.m_lMax.push_back(300);
	m_OptimGradMaxUIelmLong.m_lInc.push_back(10);
	m_OptimGradMaxUIelmLong.m_lDefault.push_back(80);
	m_OptimGradMaxUIelmLong.m_pLabel="Max Diff Grad";
	m_OptimGradMaxUIelmLong.m_lWMBindex=UIF_UI::WMB_MaxDiffGrad; 
	// invisible check box
	m_OptimInvisibleCheckBoxUIelm.m_pLabel="I should be invisible";			
	m_OptimInvisibleCheckBoxUIelm.m_lWMBindex=UIF_UI::WMB_InvisibleStuff;	// FAKE INDEX, not used in WMB we can just avoid to initialise it!!!!
	m_OptimInvisibleCheckBoxUIelm.m_bIsAvailable=false;//we don't need to initialise it
	// invisible long array 2
	m_OptimInvisibleUIelmLongArray1.m_lMin.push_back(1); 
	m_OptimInvisibleUIelmLongArray1.m_lMax.push_back(8);
	m_OptimInvisibleUIelmLongArray1.m_lInc.push_back(1);
	m_OptimInvisibleUIelmLongArray1.m_pLabel="I should be invisible";
	m_OptimInvisibleUIelmLongArray1.m_lWMBindex=UIF_UI::WMB_InvisibleStuff;	// FAKE INDEX, not used in WMB we can just avoid to initialise it!!!!
	m_OptimInvisibleUIelmLongArray1.m_bIsAvailable=false;//we don't need to initialise it
	m_OptimInvisibleUIelmLongArray1.m_lArraySize=1;
	// invisible long array 2
	m_OptimInvisibleUIelmLongArray2.m_lMin.push_back(1); 
	m_OptimInvisibleUIelmLongArray2.m_lMax.push_back(7);
	m_OptimInvisibleUIelmLongArray2.m_lInc.push_back(1);
	m_OptimInvisibleUIelmLongArray2.m_pLabel="I should be invisible";
	m_OptimInvisibleUIelmLongArray2.m_lWMBindex=UIF_UI::WMB_InvisibleStuff;	// FAKE INDEX, not used in WMB we can just avoid to initialise it!!!!
	m_OptimInvisibleUIelmLongArray2.m_bIsAvailable=false;//we don't need to initialise it
	m_OptimInvisibleUIelmLongArray2.m_lArraySize=1;
	// rise time
	m_OptimRiseTimeUIelmLong.m_lMin.push_back(5); // REG Long Elm 2
	m_OptimRiseTimeUIelmLong.m_lMax.push_back(20);
	m_OptimRiseTimeUIelmLong.m_lInc.push_back(1);
	m_OptimRiseTimeUIelmLong.m_lDefault.push_back(12);
	m_OptimRiseTimeUIelmLong.m_pLabel="rise time";
	m_OptimRiseTimeUIelmLong.m_lWMBindex=UIF_UI::WMB_RiseTime; 
	// a double array
	m_OptimUIelmDoubleArray.m_dMin.push_back(0);
	m_OptimUIelmDoubleArray.m_dMin.push_back(0);
	m_OptimUIelmDoubleArray.m_dMax.push_back(1);
	m_OptimUIelmDoubleArray.m_dMax.push_back(1);
	m_OptimUIelmDoubleArray.m_dInc.push_back(0.1);
	m_OptimUIelmDoubleArray.m_dInc.push_back(0.1);
	m_OptimUIelmDoubleArray.m_dDefault.push_back(1);
	m_OptimUIelmDoubleArray.m_dDefault.push_back(1);
	m_OptimUIelmDoubleArray.m_pLabel="Optim double";
	m_OptimUIelmDoubleArray.m_lWMBindex=UIF_UI::WMB_OptimDoubleArray_Start; // 0->16, DOUBLE
	m_OptimUIelmDoubleArray.m_lArraySize=2;
	// trigger pos selecion box
	m_UIelmSelBox.m_sOptions.push_back("before first 180");
	m_UIelmSelBox.m_sOptions.push_back("before second 180");
	m_UIelmSelBox.m_sOptions.push_back("before readout");
	m_UIelmSelBox.m_pLabel="trigger position";
	m_UIelmSelBox.m_lWMBindex=UIF_UI::WMB_TriggerPosSelBox; 
	m_UIelmSelBox.m_lNofOptions=3;
	// total Optim UIConfig
	m_OptimExtraCardUIelmSet.addElement(&m_OptimGradMaxUIelmLong);
	m_OptimExtraCardUIelmSet.addElement(&m_OptimInvisibleCheckBoxUIelm);
	m_OptimExtraCardUIelmSet.addElement(&m_OptimInvisibleUIelmLongArray1);		// will go on GRAD CARD (and VAPOR will also have one)
	m_OptimExtraCardUIelmSet.addElement(&m_OptimInvisibleUIelmLongArray2);		// will go on GRAD CARD (and VAPOR will also have one)
	m_OptimExtraCardUIelmSet.addElement(&m_OptimRiseTimeUIelmLong);
	m_OptimExtraCardUIelmSet.addElement(&m_OptimUIelmDoubleArray);
	m_OptimExtraCardUIelmSet.addElement(&m_UIelmSelBox);



	// ----------------------------------
	// THE STD CARD UI ELEMENT SET
	// ----------------------------------
	// grad duration
	m_StdDiffGradDurUIelmLong.m_lMin.push_back(1100); // true values here, FRA one where based on a 500x logic, 
	m_StdDiffGradDurUIelmLong.m_lMax.push_back(4400);
	m_StdDiffGradDurUIelmLong.m_lInc.push_back(20);
	m_StdDiffGradDurUIelmLong.m_lDefault.push_back(2200);
	m_StdDiffGradDurUIelmLong.m_pLabel="Gradient Duration";
	m_StdDiffGradDurUIelmLong.m_lWMBindex=UIF_UI::WMB_grad_dur; 
	// number of directions
	m_StdNdirUIelmLong.m_lMin.push_back(1); 
	m_StdNdirUIelmLong.m_lMax.push_back(6);
	m_StdNdirUIelmLong.m_lInc.push_back(1);
	m_StdNdirUIelmLong.m_lDefault.push_back(1);
	m_StdNdirUIelmLong.m_pLabel="# directions";
	m_StdNdirUIelmLong.m_lWMBindex=UIF_UI::WMB_ndir; 
	// number of G values
	m_StdNgvaUIelmLong.m_lMin.push_back(1); 
	m_StdNgvaUIelmLong.m_lMax.push_back(10);
	m_StdNgvaUIelmLong.m_lInc.push_back(1);
	m_StdNgvaUIelmLong.m_lDefault.push_back(1);
	m_StdNgvaUIelmLong.m_pLabel="# g values";
	m_StdNgvaUIelmLong.m_lWMBindex=UIF_UI::WMB_ngval; 
	// TOTAL std card UIConfig	
	m_StdUIelmSet.addElement(&m_StdDiffGradDurUIelmLong);
	m_StdUIelmSet.addElement(&m_StdNdirUIelmLong);
	m_StdUIelmSet.addElement(&m_StdNgvaUIelmLong);
	

	// ----------------------------------
	// Compose ***DEFAULT*** EXTRA UIELEMENT SET
	// ----------------------------------
	m_ExtraCardUIelmSet.addElement(&m_DiffGradExtraCardUIelmSet);

	// ----------------------------------
	// Compose THE GLOBAL UIELEMENT SET
	// ----------------------------------
	GLOBAL_UI_ELEMENTSET.clearElements();
	GLOBAL_UI_ELEMENTSET.addElement(&m_ExtraCardUIelmSet);
	GLOBAL_UI_ELEMENTSET.addElement(&m_StdUIelmSet);
	return ( SEQU_NORMAL );
}


// ----------------------------------
// refresh the THE GLOBAL UIELEMENT SET
// ----------------------------------
NLSStatus MiniFlash::refreshGLOBAL_UI_ELEMENTSET(void)	//												___FF___
{
	
	m_ExtraCardUIelmSet.clearElements();
	GLOBAL_UI_ELEMENTSET.clearElements();

	switch (m_lCurrentExtraCardChoice)
	{
	case UIF_UI::UIF_ExtraCardGrad:
		{
		m_ExtraCardUIelmSet.addElement(&m_DiffGradExtraCardUIelmSet);
		break;
		}
	case UIF_UI::UIF_ExtraCardVAPOR:
		{
		m_ExtraCardUIelmSet.addElement(&m_VaporExtraCardUIelmSet);
		}
		break;
	case UIF_UI::UIF_ExtraCardOptim:
		{
		m_ExtraCardUIelmSet.addElement(&m_OptimExtraCardUIelmSet);
		}
		break;
	}

	GLOBAL_UI_ELEMENTSET.addElement(&m_ExtraCardUIelmSet);
	GLOBAL_UI_ELEMENTSET.addElement(&m_StdUIelmSet);
	return ( SEQU_NORMAL );
}
#endif


NLSStatus MiniFlash::checkAndRefreshInCaseOfSelBoxesVariation(MrProt &rMrProt,SeqLim &rSeqLim)
{
	// REFRESHING the content of factory managed elements is a dynamical process, 
	// We have to check first in which context the prepare method is called. There are two reasons for this
	//	1)	the UI is not supposed to be changed during prepare. It happens that during the calls in the context
	//		for binary search the values on the card are changed and changed again, until they are not changed back  
	//		to the true values selected by the user. But the fields appareance in the GUI are not always refreshed
	//		by the system, as it do not think we are playng with card entry during prepare...
	//		Thus, if we do not specify that we want to be in the context for Scan time calculation, before changing 
	//		the UI appareance, we will have a wrong appearance on the GUI (although the values in WMB will be correct)
	//	2)	After the protocol is defined and we RUN (or SIMULATE) the sequence, all the methods (Initialize, Prepare
	//		check and run) are called again once, in context NORMAL. This time not the default, but the true protocol 
	//		is passed. Thus we need to configure all the objects in the correct way in prepare. IN the case of our
	//		Factory dependent objects, because of point 1), we have the objects reinitialised to their defaule
	//		values in Initialise, and we need them to be restored to the protocol ones in prepare. We obtain it by 
	//		repeating the true initialisation in case context in NORMAL. NB, the important point here is that all
	//		the UI entries are the correct ones, but the object defined by the factory and using those entries would be 
	//		the wrong ones.
	if (rSeqLim.isContextPrepForScanTimeCalculation()||rSeqLim.isContextNormal()) 
	{
		// we have to check if selection box option is changed after default initialization. If not changed, do nothing. 
		if (!(m_lCurrentGradSchemeChoice==rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_Selection_Box_GradScheme]))
		{
			m_pDiffusionGradientSchemeFactory=NULL;
			m_pDiffusionGradientSchemeFactory=AbstractDiffusionGradientSchemeFactory::getFactory(rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_Selection_Box_GradScheme]);
			m_pDiffusionGradientScheme=NULL;
			m_pDiffusionGradientScheme=m_pDiffusionGradientSchemeFactory->getGradientScheme();
			m_pDiffusionGradSchemeUIConfigurator=NULL;
			m_pDiffusionGradSchemeUIConfigurator=m_pDiffusionGradientSchemeFactory->getUIConfigurator();
			m_lCurrentGradSchemeChoice=rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_Selection_Box_GradScheme];
#ifdef WIN32
			m_DiffGradSchemeUIelmSet=m_pDiffusionGradSchemeUIConfigurator->getUIConfig();// it takes the member variable m_Config of the true class implementing  AbstractUIConfigurator interface
			// Here we set the UI default values to the ones decided by the new selected Grad Scheme for each position (i.e. for each REGindex). 
			// Remember, the default value of our WMB elements is only set in _Init. Because the WMB elements of our mutually exclusive Grad Schemes 
			// share the same WMB elements (there is no reason to keep all of them in WMB memory, it would be wrong indeed, as in principle as many mutually 
			// exclusive Grad Shceme classes as we want may exist) if we would not refresh the value to the default one of the new Grad Scheme, 
			// the UI would show the old value we set for the last Grad Scheme. 
			rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_LongElementForGradScheme1]=(long)(static_cast<UIelementLong*>(m_DiffGradSchemeUIelmSet.returnElementByID(UIF_UI::REG_LongElement1))->m_lDefault[0]);
			rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_LongElementForGradScheme2]=(long)(static_cast<UIelementLong*>(m_DiffGradSchemeUIelmSet.returnElementByID(UIF_UI::REG_LongElement2))->m_lDefault[0]);
			rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_GradSchemeSelBox]=(long)(static_cast<UIelementSelectionBox*>(m_DiffGradSchemeUIelmSet.returnElementByID(UIF_UI::REG_Selection_Box))->m_lDefault);
			// WE SHOULD EXECUTE THIS SECTION IF THE CURRENT EXTRA CARD IS NOT THE ONE INCLUDING GRAD SCHEME (i.e. GRAD) 
			// After re-initialising our objects (in the case a change occurred on the UI for selection Box, in context x ScanTimeCalculation
			// we refresh the GLOBAL variables used in our UI function handlers. This call is irrelevant in the case of context NORMAL
			m_DiffGradExtraCardUIelmSet.clearElements();
			m_DiffGradExtraCardUIelmSet.addElement(&m_DiffGradSchemeUIelmSet);
			m_DiffGradExtraCardUIelmSet.addElement(&m_DiffGradStdUIelmSet);
			refreshGLOBAL_UI_ELEMENTSET();
#endif			
			
		} 
		// we have to check if selection box option is changed after default initialization. If not changed, do nothing. 
		if (!( m_lCurrentExtraCardChoice==rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_Selection_Box_ExtraCard]))
		{
			m_lCurrentExtraCardChoice=rMrProt.wipMemBlock().getalFree()[UIF_UI::WMB_Selection_Box_ExtraCard];
			// just a test for a dynaimic assignment based on UI handling
			rMrProt.wipMemBlock().getadFree()[UIF_UI::WMB_DoubleElementForGradScheme] =(double)(1280*(m_lCurrentExtraCardChoice-5));
#ifdef WIN32
			refreshGLOBAL_UI_ELEMENTSET();
#endif
		} 
	}












	return ( SEQU_NORMAL );
}

